#Header: iWantToApplyPlugin
#
PlayerApps: GOLD
#
#
#BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
#
DisplayColorText: GOLD
#
DisplayColorVariables: DARK_AQUA
#
#
#
#ALL THE APPS FOLLOW HERE:
#